#!/bin/sh
export COMMON=--builddir=dist/aarch64
export COMPILE="--with-ghc=aarch64-apple-darwin14-ghc
                --with-ghc-pkg=aarch64-apple-darwin14-ghc-pkg
                --with-gcc=aarch64-apple-darwin14-clang
                --with-ld=aarch64-apple-darwin14-ld
                --hsc2hs-options=--cross-compile"
export CONFIG="--configure-option=--host=aarch64-apple-darwin14 --disable-shared"
exec "`dirname $0`/common-cross-cabal" "$@"
