#!/bin/sh
export COMMON=--builddir=dist/arm64
export COMPILE="--with-ghc=arm64-apple-darwin14-ghc
                --with-ghc-pkg=arm64-apple-darwin14-ghc-pkg
                --with-gcc=arm64-apple-darwin14-clang
                --with-ld=arm64-apple-darwin14-ld
                --hsc2hs-options=--cross-compile"
export CONFIG="--configure-option=--host=arm64-apple-darwin14 --disable-shared"
exec "`dirname $0`/common-cross-cabal" "$@"
