#!/bin/sh
TARGET_PLATFORM=`xcrun --show-sdk-path --sdk iphoneos`
# TARGET_GCC=`xcrun -f clang`
TARGET_GCC=/usr/local/opt/llvm/bin/clang
TARGET_CFLAGS="-isysroot $TARGET_PLATFORM -arch arm64 -miphoneos-version-min=7.0"

exec $TARGET_GCC $TARGET_CFLAGS "$@"