#!/bin/sh

TARGET_PLATFORM=`xcrun --show-sdk-platform-path --sdk iphoneos`
TARGET_BIN=`xcrun --sdk iphoneos -f ld`

TARGET_LD=$TARGET_BIN
TARGET_LDFLAGS="-L$TARGET_PLATFORM/usr/lib/ -arch arm64 -ios_version_min 7.0"

exec $TARGET_LD $TARGET_LDFLAGS "$@"
