#!/bin/sh
if [ ! -f Setup ]; then
    if [ -f Setup.hs -o -f Setup.lhs ]; then
        ghc --make Setup.?hs
    fi
    if [ ! -f Setup ]; then
        echo Could not find 'Setup or Setup.(l)hs'
        exit 1
    fi
fi
cp Setup dist/arm/setup/setup
if [ $# -lt 1 ]; then
    echo "Usage: $(basename $0) clean|configure|build|install"
    exit 1
fi
export COMMON=--builddir=dist/arm
export COMPILE="--with-ghc=arm-apple-darwin10-ghc
                --with-ghc-pkg=arm-apple-darwin10-ghc-pkg
                --with-gcc=arm-apple-darwin10-clang
                --with-ld=arm-apple-darwin10-ld
                --hsc2hs-options=--cross-compile"
export CONFIG="--configure-option=--host=arm-apple-darwin10 --disable-shared"
exec "`dirname $0`/common-cross-cabal" "$@"
