#!/bin/sh

TARGET_PLATFORM=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.0.sdk

TARGET_LD=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld
TARGET_LDFLAGS="-L$TARGET_PLATFORM/usr/lib/ -arch armv7s"

exec $TARGET_LD $TARGET_LDFLAGS "$@"