#!/bin/sh

set -e

# Simply multiplexes arguments over both simulator and device cabals

i386-apple-darwin11-cabal $@
arm-apple-darwin10-cabal $@
x86_64-apple-darwin14-cabal $@
aarch64-apple-darwin14-cabal $@
