#!/bin/sh

TARGET_PLATFORM=`xcrun --show-sdk-path --sdk iphonesimulator`
TARGET_GCC=`xcrun -f clang`
TARGET_CFLAGS="-isysroot $TARGET_PLATFORM -arch i386 -mios-simulator-version-min=7.0"

exec $TARGET_GCC $TARGET_CFLAGS "$@"