#!/bin/sh

SDK=iphonesimulator
ARCH=i386

# TARGET_PLATFORM=`xcrun --sdk ${SDK} --show-sdk-path`
# TARGET_GCC=`xcrun --sdk ${SDK} --find clang`
# TARGET_CFLAGS="-isysroot $TARGET_PLATFORM -arch $ARCH"

exec xcrun --sdk ${SDK} clang -arch ${ARCH} -mios-simulator-version-min=7.0 "$@"
