#!/bin/sh

TARGET_PLATFORM=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.1.sdk/

TARGET_LD=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld
TARGET_LDFLAGS="-L$TARGET_PLATFORM/usr/lib/ -arch i386"

exec $TARGET_LD $TARGET_LDFLAGS "$@"